package com.sem.nutrix.ui.theme

import android.app.Activity
import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.SideEffect
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalView
import androidx.core.view.WindowCompat

val md_theme_light_primary = Color(0xFF4E6700)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCFEF80)
val md_theme_light_onPrimaryContainer = Color(0xFF151F00)
val md_theme_light_secondary = Color(0xFF4F6603)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD0EE82)
val md_theme_light_onSecondaryContainer = Color(0xFF151F00)
val md_theme_light_tertiary = Color(0xFF006A60)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF74F8E5)
val md_theme_light_onTertiaryContainer = Color(0xFF00201C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFFE5)
val md_theme_light_onBackground = Color(0xFF141F00)
val md_theme_light_surface = Color(0xFFFAFFE5)
val md_theme_light_onSurface = Color(0xFF141F00)
val md_theme_light_surfaceVariant = Color(0xFFE2E4D4)
val md_theme_light_onSurfaceVariant = Color(0xFF45483C)
val md_theme_light_outline = Color(0xFF76786B)
val md_theme_light_inverseOnSurface = Color(0xFFD9FE92)
val md_theme_light_inverseSurface = Color(0xFF243600)
val md_theme_light_inversePrimary = Color(0xFFB3D267)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4E6700)
val md_theme_light_outlineVariant = Color(0xFFC6C8B8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB3D267)
val md_theme_dark_onPrimary = Color(0xFF273500)
val md_theme_dark_primaryContainer = Color(0xFF3A4D00)
val md_theme_dark_onPrimaryContainer = Color(0xFFCFEF80)
val md_theme_dark_secondary = Color(0xFFB4D269)
val md_theme_dark_onSecondary = Color(0xFF273500)
val md_theme_dark_secondaryContainer = Color(0xFF3A4D00)
val md_theme_dark_onSecondaryContainer = Color(0xFFD0EE82)
val md_theme_dark_tertiary = Color(0xFF53DBC9)
val md_theme_dark_onTertiary = Color(0xFF003731)
val md_theme_dark_tertiaryContainer = Color(0xFF005048)
val md_theme_dark_onTertiaryContainer = Color(0xFF74F8E5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF141F00)
val md_theme_dark_onBackground = Color(0xFFCBEF86)
val md_theme_dark_surface = Color(0xFF141F00)
val md_theme_dark_onSurface = Color(0xFFCBEF86)
val md_theme_dark_surfaceVariant = Color(0xFF45483C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C8B8)
val md_theme_dark_outline = Color(0xFF909284)
val md_theme_dark_inverseOnSurface = Color(0xFF141F00)
val md_theme_dark_inverseSurface = Color(0xFFCBEF86)
val md_theme_dark_inversePrimary = Color(0xFF4E6700)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB3D267)
val md_theme_dark_outlineVariant = Color(0xFF45483C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF4E6700)
val Error = Color(0xFFBA1B1B)
val Neutral_Variant = Color(0xFF5D5F53)
val light_Error = Color(0xFFBA1B1B)
val light_onError = Color(0xFFFFFFFF)
val light_ErrorContainer = Color(0xFFFFDAD6)
val light_onErrorContainer = Color(0xFF410002)
val dark_Error = Color(0xFFFFB4AB)
val dark_onError = Color(0xFF690005)
val dark_ErrorContainer = Color(0xFF93000A)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val light_NeutralVariant = Color(0xFF506601)
val light_onNeutralVariant = Color(0xFFFFFFFF)
val light_NeutralVariantContainer = Color(0xFFD1EE81)
val light_onNeutralVariantContainer = Color(0xFF161F00)
val dark_NeutralVariant = Color(0xFFB5D168)
val dark_onNeutralVariant = Color(0xFF283500)
val dark_NeutralVariantContainer = Color(0xFF3B4D00)
val dark_onNeutralVariantContainer = Color(0xFFD1EE81)

val NeutralColor = Color(0xFF78909C)
val HappyColor = Color(0xFFFFEE58)
val RomanticColor = Color(0xFFEC407A)
val CalmColor = Color(0xFF42A5F5)
val TenseColor = Color(0xFFFF7043)
val LonelyColor = Color(0xFF8D6E63)
val MysteriousColor = Color(0xFF26A69A)
val AngryColor = Color(0xFFEF5350)
val AwfulColor = Color(0xFF66BB6A)
val SurprisedColor = Color(0xFF29B6F6)
val DepressedColor = Color(0xFFBDBDBD)
val DisappointedColor = Color(0xFFAB47BC)
val ShamefulColor = Color(0xFF7E57C2)
val HumorousColor = Color(0xFFFFCA28)
val SuspiciousColor = Color(0xFFD4E157)
val BoredColor = Color(0xFF26C6DA)